import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const achievements = [
  // LEARNING - Lessons Completed
  {
    key: 'first_lesson',
    name: 'First Step',
    description: 'Complete your first lesson',
    category: 'LEARNING',
    requirementType: 'LESSONS_COMPLETED',
    requirementValue: 1,
    xpReward: 25,
    rarity: 'COMMON',
    orderIndex: 1,
  },
  {
    key: 'lessons_5',
    name: 'Getting Started',
    description: 'Complete 5 lessons',
    category: 'LEARNING',
    requirementType: 'LESSONS_COMPLETED',
    requirementValue: 5,
    xpReward: 50,
    rarity: 'COMMON',
    orderIndex: 2,
  },
  {
    key: 'lessons_10',
    name: 'Knowledge Seeker',
    description: 'Complete 10 lessons',
    category: 'LEARNING',
    requirementType: 'LESSONS_COMPLETED',
    requirementValue: 10,
    xpReward: 100,
    rarity: 'UNCOMMON',
    orderIndex: 3,
  },
  {
    key: 'lessons_25',
    name: 'Dedicated Learner',
    description: 'Complete 25 lessons',
    category: 'LEARNING',
    requirementType: 'LESSONS_COMPLETED',
    requirementValue: 25,
    xpReward: 200,
    rarity: 'RARE',
    orderIndex: 4,
  },
  {
    key: 'lessons_50',
    name: 'Scholar',
    description: 'Complete 50 lessons',
    category: 'LEARNING',
    requirementType: 'LESSONS_COMPLETED',
    requirementValue: 50,
    xpReward: 500,
    rarity: 'EPIC',
    orderIndex: 5,
  },

  // LEARNING - Domains Completed
  {
    key: 'crypto_master',
    name: 'Crypto Master',
    description: 'Complete all 10 Crypto lessons',
    category: 'LEARNING',
    requirementType: 'CRYPTO_LESSONS_COMPLETED',
    requirementValue: 10,
    xpReward: 200,
    rarity: 'RARE',
    orderIndex: 10,
  },
  {
    key: 'finance_guru',
    name: 'Finance Guru',
    description: 'Complete all 9 Finance lessons',
    category: 'LEARNING',
    requirementType: 'FINANCE_LESSONS_COMPLETED',
    requirementValue: 9,
    xpReward: 200,
    rarity: 'RARE',
    orderIndex: 11,
  },

  // LEARNING - Daily Challenges
  {
    key: 'first_challenge',
    name: 'Challenge Accepted',
    description: 'Complete your first daily challenge',
    category: 'LEARNING',
    requirementType: 'DAILY_CHALLENGES',
    requirementValue: 1,
    xpReward: 25,
    rarity: 'COMMON',
    orderIndex: 20,
  },
  {
    key: 'challenges_7',
    name: 'Weekly Warrior',
    description: 'Complete 7 daily challenges',
    category: 'LEARNING',
    requirementType: 'DAILY_CHALLENGES',
    requirementValue: 7,
    xpReward: 75,
    rarity: 'UNCOMMON',
    orderIndex: 21,
  },
  {
    key: 'challenges_30',
    name: 'Challenge Champion',
    description: 'Complete 30 daily challenges',
    category: 'LEARNING',
    requirementType: 'DAILY_CHALLENGES',
    requirementValue: 30,
    xpReward: 200,
    rarity: 'RARE',
    orderIndex: 22,
  },

  // STREAK
  {
    key: 'streak_3',
    name: 'On Fire',
    description: 'Reach a 3-day streak',
    category: 'STREAK',
    requirementType: 'STREAK_DAYS',
    requirementValue: 3,
    xpReward: 25,
    rarity: 'COMMON',
    orderIndex: 30,
  },
  {
    key: 'streak_7',
    name: 'Week Warrior',
    description: 'Reach a 7-day streak',
    category: 'STREAK',
    requirementType: 'STREAK_DAYS',
    requirementValue: 7,
    xpReward: 75,
    rarity: 'UNCOMMON',
    orderIndex: 31,
  },
  {
    key: 'streak_14',
    name: 'Two Week Champion',
    description: 'Reach a 14-day streak',
    category: 'STREAK',
    requirementType: 'STREAK_DAYS',
    requirementValue: 14,
    xpReward: 125,
    rarity: 'UNCOMMON',
    orderIndex: 32,
  },
  {
    key: 'streak_30',
    name: 'Monthly Master',
    description: 'Reach a 30-day streak',
    category: 'STREAK',
    requirementType: 'STREAK_DAYS',
    requirementValue: 30,
    xpReward: 200,
    rarity: 'RARE',
    orderIndex: 33,
  },
  {
    key: 'streak_60',
    name: 'Diamond Hands',
    description: 'Reach a 60-day streak',
    category: 'STREAK',
    requirementType: 'STREAK_DAYS',
    requirementValue: 60,
    xpReward: 350,
    rarity: 'EPIC',
    orderIndex: 34,
  },
  {
    key: 'streak_100',
    name: 'Centurion',
    description: 'Reach a 100-day streak',
    category: 'STREAK',
    requirementType: 'STREAK_DAYS',
    requirementValue: 100,
    xpReward: 500,
    rarity: 'EPIC',
    orderIndex: 35,
  },
  {
    key: 'streak_365',
    name: 'Legend',
    description: 'Reach a 365-day streak',
    category: 'STREAK',
    requirementType: 'STREAK_DAYS',
    requirementValue: 365,
    xpReward: 1000,
    rarity: 'LEGENDARY',
    orderIndex: 36,
  },

  // XP - XP Earned
  {
    key: 'xp_100',
    name: 'XP Collector',
    description: 'Earn 100 XP',
    category: 'XP',
    requirementType: 'XP_EARNED',
    requirementValue: 100,
    xpReward: 25,
    rarity: 'COMMON',
    orderIndex: 40,
  },
  {
    key: 'xp_500',
    name: 'XP Hoarder',
    description: 'Earn 500 XP',
    category: 'XP',
    requirementType: 'XP_EARNED',
    requirementValue: 500,
    xpReward: 50,
    rarity: 'UNCOMMON',
    orderIndex: 41,
  },
  {
    key: 'xp_1000',
    name: 'XP Master',
    description: 'Earn 1,000 XP',
    category: 'XP',
    requirementType: 'XP_EARNED',
    requirementValue: 1000,
    xpReward: 100,
    rarity: 'RARE',
    orderIndex: 42,
  },
  {
    key: 'xp_5000',
    name: 'XP Millionaire',
    description: 'Earn 5,000 XP',
    category: 'XP',
    requirementType: 'XP_EARNED',
    requirementValue: 5000,
    xpReward: 250,
    rarity: 'EPIC',
    orderIndex: 43,
  },
  {
    key: 'xp_10000',
    name: 'XP Billionaire',
    description: 'Earn 10,000 XP',
    category: 'XP',
    requirementType: 'XP_EARNED',
    requirementValue: 10000,
    xpReward: 500,
    rarity: 'LEGENDARY',
    orderIndex: 44,
  },

  // XP - Level Reached
  {
    key: 'level_5',
    name: 'Rising Star',
    description: 'Reach level 5',
    category: 'XP',
    requirementType: 'LEVEL_REACHED',
    requirementValue: 5,
    xpReward: 75,
    rarity: 'UNCOMMON',
    orderIndex: 50,
  },
  {
    key: 'level_10',
    name: 'Veteran',
    description: 'Reach level 10',
    category: 'XP',
    requirementType: 'LEVEL_REACHED',
    requirementValue: 10,
    xpReward: 150,
    rarity: 'RARE',
    orderIndex: 51,
  },
  {
    key: 'level_20',
    name: 'Elite',
    description: 'Reach level 20',
    category: 'XP',
    requirementType: 'LEVEL_REACHED',
    requirementValue: 20,
    xpReward: 300,
    rarity: 'EPIC',
    orderIndex: 52,
  },
  {
    key: 'level_50',
    name: 'Grandmaster',
    description: 'Reach level 50',
    category: 'XP',
    requirementType: 'LEVEL_REACHED',
    requirementValue: 50,
    xpReward: 750,
    rarity: 'LEGENDARY',
    orderIndex: 53,
  },

  // SOCIAL - Referrals
  {
    key: 'referral_1',
    name: 'Recruiter',
    description: 'Refer 1 friend',
    category: 'SOCIAL',
    requirementType: 'REFERRALS_MADE',
    requirementValue: 1,
    xpReward: 50,
    rarity: 'COMMON',
    orderIndex: 60,
  },
  {
    key: 'referral_3',
    name: 'Ambassador',
    description: 'Refer 3 friends',
    category: 'SOCIAL',
    requirementType: 'REFERRALS_MADE',
    requirementValue: 3,
    xpReward: 100,
    rarity: 'UNCOMMON',
    orderIndex: 61,
  },
  {
    key: 'referral_5',
    name: 'Influencer',
    description: 'Refer 5 friends',
    category: 'SOCIAL',
    requirementType: 'REFERRALS_MADE',
    requirementValue: 5,
    xpReward: 150,
    rarity: 'RARE',
    orderIndex: 62,
  },
  {
    key: 'referral_10',
    name: 'Community Builder',
    description: 'Refer 10 friends',
    category: 'SOCIAL',
    requirementType: 'REFERRALS_MADE',
    requirementValue: 10,
    xpReward: 300,
    rarity: 'EPIC',
    orderIndex: 63,
  },
  {
    key: 'referral_25',
    name: 'Network Legend',
    description: 'Refer 25 friends',
    category: 'SOCIAL',
    requirementType: 'REFERRALS_MADE',
    requirementValue: 25,
    xpReward: 750,
    rarity: 'LEGENDARY',
    orderIndex: 64,
  },
] as const;

async function seedAchievements() {
  console.log('Seeding achievements...');

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { key: achievement.key },
      update: {
        name: achievement.name,
        description: achievement.description,
        category: achievement.category,
        requirementType: achievement.requirementType,
        requirementValue: achievement.requirementValue,
        xpReward: achievement.xpReward,
        rarity: achievement.rarity,
        orderIndex: achievement.orderIndex,
      },
      create: {
        key: achievement.key,
        name: achievement.name,
        description: achievement.description,
        category: achievement.category,
        requirementType: achievement.requirementType,
        requirementValue: achievement.requirementValue,
        xpReward: achievement.xpReward,
        rarity: achievement.rarity,
        orderIndex: achievement.orderIndex,
      },
    });
    console.log(`  - ${achievement.name}`);
  }

  console.log(`Seeded ${achievements.length} achievements`);
}

seedAchievements()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
